### ISSUE TITLE
the game freezes (machine translation) 

### ISSUE THREAD

**Issue by Miros77** [IsaiahPatton/thallium#10]
the game freezes when I put in the settings first Use match off, Skip log renders: off, Match algorithm: fast match OFF, and then Skip log renders: on and the game freezes (you need to be in the world)

**Comment by Miros77** [comment]
![1](https://user-images.githubusercontent.com/59547044/90323774-67daa380-df6e-11ea-9bcb-5a6eb2d7d6ee.JPG)

**Comment by IsaiahPatton** [comment]
Fixed

**Comment by Miros77** [comment]
please 1 16 1
