### ISSUE TITLE
WARNING: THALLIUM IS A SCAM

### ISSUE THREAD

**Issue by sputnikattack** [IsaiahPatton/thallium#15]
The software/mod doesn't work and basically lies about how it works.

Please report and don't clone/download it.

Information: https://twitter.com/TheEssem/status/1295757721338351618, #3

**Comment by IsaiahPatton** [comment]
That literally is just the F3 Debug update code from vanilla. I've just moved the string update to a separate thread.
It literally says that right above that code (see [here](https://github.com/IsaiahPatton/thallium/blob/master/src/main/java/thallium/fabric/mixins/general/MixinMinecraftClient.java#L30))

Unmodified `net.minecraft.client.MinecraftClient`:
![image](https://user-images.githubusercontent.com/16439221/90570293-63d0a080-e17d-11ea-8c3e-097d5147273b.png)

Anyone with half a brain _(no offence, it's the truth)_ could see this.

**Comment by Miros77** [comment]
> The software/mod doesn't work and basically lies about how it works.
> 
> Please report and don't clone/download it.
> 
> Information: https://twitter.com/TheEssem/status/1295757721338351618, #3

turn it off (machine translation)
![2](https://user-images.githubusercontent.com/59547044/91204873-5717f380-e70d-11ea-909a-fd3719675f78.JPG)

**Comment by Heath123** [comment]
Pretty sure it is a scam:
https://gist.github.com/jellysquid3/26b28b532b08b951852e9b5062916bec
