### ISSUE TITLE
Thalium Options button overlaps pre-existing BBOR options button.

### ISSUE THREAD

**Issue by Xastabus** [IsaiahPatton/thallium#17]
While upgrading to 1.16.2 I discovered the new Thalium Options button uses the same space BBOR's options button already occupied.

![BBOR-Thallium-Button-Overlap](https://user-images.githubusercontent.com/1816386/91343120-099d9400-e7aa-11ea-86cf-43b6d94c7664.PNG)

**Comment by Xastabus** [comment]
This is the newly added button on the main Options page that was added as a workaround for Sodium overriding the standard Video Settings interface.

**Comment by Miros77** [comment]
> This is the newly added button on the main Options page that was added as a workaround for Sodium overriding the standard Video Settings interface.

actually there was a way to get into the thallium menu
![1](https://user-images.githubusercontent.com/59547044/91624381-b2b1dd80-e9a8-11ea-8d55-2f49ae8312b9.JPG)
then
Shift+P
![2](https://user-images.githubusercontent.com/59547044/91624392-c3625380-e9a8-11ea-9d4c-27b10f08a37c.JPG)

**Comment by Xastabus** [comment]
I'm testing on 1.16.2, Sodium is not updated or running on the client for this report.

**Comment by IsaiahPatton** [comment]
Fixed in update
