### ISSUE TITLE
Thallium is in violation of Sodium's licensing 

### ISSUE THREAD

**Issue by jellysquid3** [IsaiahPatton/thallium#3]
I am an authorized copyright holder for the open-source project [Sodium](https://github.com/jellysquid3/sodium-fabric).
 
Thallium is including sources from which I represent in a manner that infringes upon the [free and open-source GNU LGPLv3 license](https://github.com/jellysquid3/sodium-fabric/blob/1.16.x/dev/LICENSE.txt) they are made available under. This license, as a non-exhaustive list, requires the inclusion of the original copyright notice and prohibits the incorporation of one's project into another proprietary product.

I believe in good-faith that the following files in Thallium are including copyrighted sources of which I am the holder of and are doing so in a manner which violates the license terms made available above. Thallium is a proprietary product which is incompatible with the copyleft requirements. No attribution has been made to the original copyright holders. The inclusion of these copyrighted works [are advertised](https://www.curseforge.com/minecraft/mc-mods/thallium) on the product's landing page.

**SodiumChunkManager.java**
Infringing code in Thallium: [GitHub](https://github.com/IsaiahPatton/thallium/blob/master/src/main/java/thallium/fabric/chunk/ThalliumClientChunkManager.java)
Original sources: [GitHub](https://github.com/jellysquid3/sodium-fabric/blob/1.16.x/dev/src/main/java/me/jellysquid/mods/sodium/client/world/SodiumChunkManager.java)

Please remove the copyrighted code from your project immediately.

If I have not received an affirmative response from the project holders to Thallium by August 9th indicating that the copyrighted works have been removed, I shall consider taking any and all legal remedies available to me to rectify this situation.

**Comment by Leo40Git** [comment]
`Sodium thinks they own every fastutil implementation.` excuse me
I would like everyone who reads this to compare the following files:
[Thallium (before the commit that removed it)](https://github.com/IsaiahPatton/thallium/blob/bd65217475e004c97f28305a4000f7f69101f8a1/src/main/java/thallium/fabric/chunk/ThalliumClientChunkManager.java)
[Sodium](https://github.com/jellysquid3/sodium-fabric/blob/1.16.x/dev/src/main/java/me/jellysquid/mods/sodium/client/world/SodiumChunkManager.java)
Now look me in the eyes and tell me these aren't eerily similar...

**Comment by Leo40Git** [comment]
Also see the other 2 issues on this repository. #1 is calling the author out, while #2 seems like a genuine issue that got ignored.

**Comment by Leo40Git** [comment]
Well, you've re-licensed to LGPLv3 (which is, interestingly, the exact same license as Sodium, how about that!)

**Comment by TelepathicGrunt** [comment]
Furthermore, the license is inconsistent everywhere as well. It is All Rights Reserved on curseforge, GPLv3 in the fabric.mod.json, and LGPL in LGPL.txt. Thus this mod is still violating the license of everyone as well.

**Comment by IsaiahPatton** [comment]
Fixed in 1.4
